"""One-shot migration: dump every YAML-serializable entry of _CONFIGS to configs/_examples/.

Configs that can't be serialized (lambdas, dynamically generated by RoboArena, etc.)
are skipped and reported. They stay in _CONFIGS as Python-only.

Usage:
    python scripts/migrate_configs_to_yaml.py
    python scripts/migrate_configs_to_yaml.py --output-dir configs/_examples --overwrite
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import openpi.training.config as _config
import openpi.training.yaml_loader as _yaml_loader


def migrate(output_dir: pathlib.Path, overwrite: bool) -> tuple[list[str], list[tuple[str, str]]]:
    """Write one YAML per serializable config. Returns (written, skipped) lists."""
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    skipped: list[tuple[str, str]] = []  # (name, reason)

    for cfg in _config._CONFIGS:  # noqa: SLF001
        target = output_dir / f"{cfg.name}.yaml"
        if target.exists() and not overwrite:
            skipped.append((cfg.name, f"exists, skipping (use --overwrite to replace): {target}"))
            continue
        try:
            yaml_text = _yaml_loader.dump(cfg)
        except ValueError as exc:
            skipped.append((cfg.name, str(exc).splitlines()[0]))
            continue

        # Sanity check: re-parse and compare against the original.
        try:
            reloaded = _yaml_loader.loads(yaml_text, name=cfg.name)
        except Exception as exc:  # noqa: BLE001
            skipped.append((cfg.name, f"reload failed: {exc!r}"))
            continue
        if reloaded != cfg:
            skipped.append((cfg.name, "round-trip dataclass equality failed"))
            continue

        target.write_text(yaml_text)
        written.append(cfg.name)

    return written, skipped


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=pathlib.Path,
        default=pathlib.Path("configs/_examples"),
        help="Where to write the YAML files (default: configs/_examples)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing YAML files in --output-dir",
    )
    args = parser.parse_args()

    written, skipped = migrate(args.output_dir, args.overwrite)

    print(f"\n=== migration summary ===")
    print(f"wrote {len(written)} YAML file(s) to {args.output_dir}")
    for name in written:
        print(f"  + {name}.yaml")

    if skipped:
        print(f"\nskipped {len(skipped)} config(s):")
        for name, reason in skipped:
            print(f"  - {name}: {reason}")
        # Exit code 0 even with skips - those are expected (lambdas, RoboArena).

    if not written:
        print("\nNo configs were written. Either everything is unserializable, or all targets already exist.")
        sys.exit(1)


if __name__ == "__main__":
    main()
